-- MySQL Script generated by MySQL Workbench
-- pon, 25 sty 2016, 19:51:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nowa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nowa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nowa` ;
USE `nowa` ;

-- -----------------------------------------------------
-- Table `nowa`.`Pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Pracownik` (
  `id_pracownika` INT(11) NOT NULL COMMENT '',
  `imie_pracownika` VARCHAR(45) NOT NULL COMMENT '',
  `nazwisko_pracownika` VARCHAR(45) NOT NULL COMMENT '',
  `tytul_naukowy` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pracownika`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nowa`.`Rodzaj_studiów`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Rodzaj_studiów` (
  `id_rodzaj_studiów` INT(11) NOT NULL COMMENT '',
  `rodzaj_studiów` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_rodzaj_studiów`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nowa`.`Praca_dyplomowa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Praca_dyplomowa` (
  `id_pracy` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `temat_pracy` VARCHAR(200) NOT NULL COMMENT '',
  `id_promotora` INT(11) NULL DEFAULT NULL COMMENT '',
  `ocena` INT(11) NULL DEFAULT NULL COMMENT '',
  `data_obrony` DATE NULL DEFAULT NULL COMMENT '',
  `rodzaj_studiow` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pracy`)  COMMENT '',
  INDEX `fk_Praca dyplomowa_Rodzaj studiów1_idx` (`rodzaj_studiow` ASC)  COMMENT '',
  INDEX `fk_Praca dyplomowa_Pracownik1_idx` (`id_promotora` ASC)  COMMENT '',
  CONSTRAINT `fk_Praca dyplomowa_Pracownik1`
    FOREIGN KEY (`id_promotora`)
    REFERENCES `nowa`.`Pracownik` (`id_pracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Praca dyplomowa_Rodzaj studiów1`
    FOREIGN KEY (`rodzaj_studiow`)
    REFERENCES `nowa`.`Rodzaj_studiów` (`id_rodzaj_studiów`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nowa`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Student` (
  `numer_indeksu` INT(11) NOT NULL COMMENT '',
  `imie_studenta` VARCHAR(45) NOT NULL COMMENT '',
  `nazwisko_studenta` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`numer_indeksu`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nowa`.`Autorzy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Autorzy` (
  `id_pracy` INT(11) NOT NULL COMMENT '',
  `nr_indeksu_autora` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pracy`, `nr_indeksu_autora`)  COMMENT '',
  INDEX `fk_Autorzy_Student1_idx` (`nr_indeksu_autora` ASC)  COMMENT '',
  CONSTRAINT `fk_Autorzy_Praca dyplomowa1`
    FOREIGN KEY (`id_pracy`)
    REFERENCES `nowa`.`Praca_dyplomowa` (`id_pracy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autorzy_Student1`
    FOREIGN KEY (`nr_indeksu_autora`)
    REFERENCES `nowa`.`Student` (`numer_indeksu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nowa`.`Recenzja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Recenzja` (
  `id_pracy` INT(11) NOT NULL COMMENT '',
  `id_pracownika` INT(11) NOT NULL COMMENT '',
  `ocena_recenzenta` INT(11) NULL DEFAULT NULL COMMENT '',
  INDEX `fk_Recenzja_Pracownik1_idx` (`id_pracownika` ASC)  COMMENT '',
  PRIMARY KEY (`id_pracy`, `id_pracownika`)  COMMENT '',
  CONSTRAINT `fk_Recenzja_Praca dyplomowa1`
    FOREIGN KEY (`id_pracy`)
    REFERENCES `nowa`.`Praca_dyplomowa` (`id_pracy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recenzja_Pracownik1`
    FOREIGN KEY (`id_pracownika`)
    REFERENCES `nowa`.`Pracownik` (`id_pracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nowa`.`Słowo kluczowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Słowo kluczowe` (
  `słowo_kluczowe` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`słowo_kluczowe`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nowa`.`Słowa_kluczowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nowa`.`Słowa_kluczowe` (
  `id_pracy` INT(11) NOT NULL COMMENT '',
  `słowo_kluczowe_1` VARCHAR(45) NOT NULL COMMENT '',
  INDEX `fk_Słowa kluczowe_Słowo kluczowe1_idx` (`słowo_kluczowe_1` ASC)  COMMENT '',
  PRIMARY KEY (`id_pracy`, `słowo_kluczowe_1`)  COMMENT '',
  CONSTRAINT `fk_Słowa kluczowe_Praca dyplomowa1`
    FOREIGN KEY (`id_pracy`)
    REFERENCES `nowa`.`Praca_dyplomowa` (`id_pracy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Słowa kluczowe_Słowo kluczowe1`
    FOREIGN KEY (`słowo_kluczowe_1`)
    REFERENCES `nowa`.`Słowo kluczowe` (`słowo_kluczowe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
